events/urls.py
from django.urls import path
from .views import ListEventsView, DetailEventView, EventCreateView, EventDeleteView, EventUpdateView

app_name = 'events'

urlpatterns = [
    path('topic/<int:pk>', ListEventsView.as_view(), name='events'),
    path('<int:pk>', DetailEventView.as_view(), name='view-event'),
    path('<int:pk>/add-event', EventCreateView.as_view(), name="add-event"),
    path('<int:pk>/delete-event', EventDeleteView.as_view(), name="delete-event"),
    path('<int:pk>/update-event', EventUpdateView.as_view(), name="update-event"),
]

forum/urls.py
from django.urls import path
from .views import CommentCreateView, TopicListView, TopicCreateView, TopicUpdateView, TopicDeleteView, TopicView, \
    PostCreateView, \
    PostUpdateView, PostDeleteView, PostView, CommentDeleteView, CommentUpdateView, PostLikeView, CommentLikeView

app_name = 'forum'

urlpatterns = [
    path('', TopicListView.as_view(), name="topics"),
    path('add-topic', TopicCreateView.as_view(), name="add-topic"),
    path('topic/<int:pk>/update/', TopicUpdateView.as_view(), name="update-topic"),
    path('topic/<int:pk>/delete/', TopicDeleteView.as_view(), name="delete-topic"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="update-post"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="delete-post"),
    path('post/<int:pk>/', PostView.as_view(), name="view-post"),
    path('topic/<int:pk>/', TopicView.as_view(), name="view-topic"),
    path('topic/<int:pk>/add-post', PostCreateView.as_view(), name="add-post"),
    path('post/<int:pk>/add-comment', CommentCreateView.as_view(), name="add-comment"),
    path('comment/<int:pk>/delete-comment', CommentDeleteView.as_view(), name="delete-comment"),
    path('comment/<int:pk>/update-comment', CommentUpdateView.as_view(), name="update-comment"),
    path('post/<int:pk>/like-post', PostLikeView.as_view(), name="like-post"),
    path('comment/<int:pk>/like-comment', CommentLikeView.as_view(), name="like-comment"),
]

uniforum/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import Homepage

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'))),
    path('users/', include('django.contrib.auth.urls')),
    path('forum/', include(('forum.urls', 'forum'))),
    path('events/', include(('events.urls', 'events'))),
    path('reviews/', include(('reviews.urls', 'reviews'))),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/models.py
from django.db import models
from forum.models import Topic
from tinymce.models import HTMLField


class Event(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    start_date = models.DateField(blank=False, null=False)
    start_time = models.TimeField(blank=True, null=True)
    description = HTMLField(blank=True, null=True)

    def __str__(self):
        return f"{self.topic} - {self.title}"

events/forms.py
from django import forms
from .models import Event


class EventCreationForm(forms.ModelForm):

    class Meta(forms.ModelForm):
        model = Event
        fields = ("title", "start_date", "start_time", "description")
        widgets = {
            'start_date': forms.DateInput(format=('%Y-%m-%d'),
                                             attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                                    'type': 'date'}),
            'start_time': forms.TimeInput(format='%H:%M',
                                          attrs={'class': 'form-control', 'placeholder': 'Select a timetable',
                                                 'type': "time"}),
        }


class EventUpdateForm(forms.ModelForm):

    class Meta(forms.ModelForm):
        model = Event
        fields = ("title", "start_date", "start_time", "description")
        widgets = {
            'start_date': forms.DateInput(format=('%Y-%m-%d'),
                                          attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                                 'type': 'date'}),
            'start_time': forms.TimeInput(format='%H:%M',
                                          attrs={'class': 'form-control', 'placeholder': 'Select a timetable',
                                                 'type': "time"}),
        }

events/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from forum.models import Topic
from .forms import EventCreationForm, EventUpdateForm
from .models import Event


class ListEventsView(ListView):
    template_name = "events/events.html"
    model = Event

    def get_context_data(self, **kwargs):
        context = super(ListEventsView, self).get_context_data(**kwargs)
        context['topic'] = get_object_or_404(Topic, pk=self.kwargs['pk'])
        return context

    def get_queryset(self):
        objects = self.model.objects.all()
        objects = objects.filter(topic=self.kwargs['pk'])
        return objects


class DetailEventView(DetailView):
    template_name = "events/view_event.html"
    model = Event


class EventCreateView(SuccessMessageMixin, PermissionRequiredMixin, CreateView):
    permission_required = "events.add_event"
    form_class = EventCreationForm
    template_name = "events/add_event.html"
    model = Event
    success_message = "Event created successfully!"

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('events:events', kwargs={'pk': pk})

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.topic = get_object_or_404(Topic, pk=self.kwargs['pk'])
        return super().form_valid(form)


class EventDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "events.delete_event"
    model = Event
    template_name = 'events/delete_event.html'
    success_message = "Event deleted successfully!"

    def get_success_url(self):
        return reverse_lazy('events:events', kwargs={"pk": self.get_object().topic.pk})

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(EventDeleteView, self).delete(request, *args, **kwargs)


class EventUpdateView(SuccessMessageMixin, PermissionRequiredMixin, UpdateView):
    permission_required = "events.change_event"
    model = Event
    template_name = 'events/update_event.html'
    form_class = EventUpdateForm
    success_message = "Event updated successfully!"

    def get_success_url(self):
        return reverse_lazy('events:events', kwargs={"pk": self.get_object().topic.pk})

events/templates/events/add_event.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Add Event{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Add Event</h1>
        </div>
    </div>
    <form method="POST" >
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Add Event</button>
    </form>

{% endblock %}

events/templates/events/delete_event.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Delete Event{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Delete Event</h1>
        </div>
    </div>
    <form method="POST" class="mt-4" >
        {% csrf_token %}
        <h3 class="font-weight-light">Are you sure you want to delete <b>{{ object.title }} {{ object.start_date }}{% if object.start_time %} - {{ object.start_time }}{% endif %}</b> event?</h3>
        <button type="submit" class="btn btn-danger mt-4">Delete Event</button>
    </form>

{% endblock %}

events/templates/events/events.html
{% extends 'base.html' %}
{% load static %}
{% load has_group %}

{% block head %}
    {% block title %}Events{% endblock %}
    <link href='https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.1/css/all.css' rel='stylesheet'>

    <link href='https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/main.min.css' rel='stylesheet' />
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/main.min.js'></script>

{% endblock %}

{% block content %}
    <h1 class="d-inline">Events - {{ topic }}</h1>
    {% if user|has_group:"mods" %}
    <div class="d-inline">
        <a href="{% url 'events:add-event' topic.pk %}" class="btn btn-outline-primary mb-3 ml-3" ><i class="bi bi-plus-lg"></i></a>
    </div>
    {% endif %}
    <div id='calendar' class="mt-4"></div>


{% endblock %}
{% block javascript %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                themeSystem: 'bootstrap',
                headerToolbar: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
                },
                events: [
                    {% for event in event_list %}
                    {
                        title: '{{ event.title }}',
                        start: '{{ event.start_date.isoformat }}{% if event.start_time %} {{ event.start_time.isoformat }}{% endif %}',
                        url: '{% url 'events:view-event' event.pk %}',
                    },
                    {% endfor %}
                ]
            });
            calendar.render();
        });
    </script>
{% endblock %}

events/templates/events/update_event.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Update Event{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Update Event</h1>
        </div>
    </div>
    <form method="POST" >
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update Event</button>
    </form>

{% endblock %}

events/templates/events/view_event.html
{% extends 'base.html' %}
{% load static %}
{% load has_group %}
{% block title %}{{ event.title }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>{{ event.title }}</h1>
            <div class="col-2 float-right">
                {% if user|has_group:"mods" %}
                    <a href="{% url 'events:delete-event' event.pk %}" class="btn btn-danger mb-2 mr-2" ><i class="bi bi-trash"></i></a>
                    <a href="{% url 'events:update-event' event.pk %}" class="btn btn-secondary mb-2" ><i class="bi bi-pencil"></i></a>
                {% endif %}
            </div>
            <h3>{{ event.start_date }}{% if event.start_time %} - {{ event.start_time }}{% endif %}</h3>
            <div class="mt-4">
                <hr class="mb-4"/>
                {% if event.description %}
                {{ event.description|safe }}
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}