events/urls.py
from django.urls import path
from .views import ListEventsView, DetailEventView, EventCreateView, EventDeleteView, EventUpdateView

app_name = 'events'

urlpatterns = [
    path('topic/<int:pk>', ListEventsView.as_view(), name='events'),
    path('<int:pk>', DetailEventView.as_view(), name='view-event'),
    path('<int:pk>/add-event', EventCreateView.as_view(), name="add-event"),
    path('<int:pk>/delete-event', EventDeleteView.as_view(), name="delete-event"),
    path('<int:pk>/update-event', EventUpdateView.as_view(), name="update-event"),
]

forum/urls.py
from django.urls import path
from .views import CommentCreateView, TopicListView, TopicCreateView, TopicUpdateView, TopicDeleteView, TopicView, \
    PostCreateView, \
    PostUpdateView, PostDeleteView, PostView, CommentDeleteView, CommentUpdateView, PostLikeView, CommentLikeView

app_name = 'forum'

urlpatterns = [
    path('', TopicListView.as_view(), name="topics"),
    path('add-topic', TopicCreateView.as_view(), name="add-topic"),
    path('topic/<int:pk>/update/', TopicUpdateView.as_view(), name="update-topic"),
    path('topic/<int:pk>/delete/', TopicDeleteView.as_view(), name="delete-topic"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="update-post"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="delete-post"),
    path('post/<int:pk>/', PostView.as_view(), name="view-post"),
    path('topic/<int:pk>/', TopicView.as_view(), name="view-topic"),
    path('topic/<int:pk>/add-post', PostCreateView.as_view(), name="add-post"),
    path('post/<int:pk>/add-comment', CommentCreateView.as_view(), name="add-comment"),
    path('comment/<int:pk>/delete-comment', CommentDeleteView.as_view(), name="delete-comment"),
    path('comment/<int:pk>/update-comment', CommentUpdateView.as_view(), name="update-comment"),
    path('post/<int:pk>/like-post', PostLikeView.as_view(), name="like-post"),
    path('comment/<int:pk>/like-comment', CommentLikeView.as_view(), name="like-comment"),
]

uniforum/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import Homepage

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'))),
    path('users/', include('django.contrib.auth.urls')),
    path('forum/', include(('forum.urls', 'forum'))),
    path('events/', include(('events.urls', 'events'))),
    path('reviews/', include(('reviews.urls', 'reviews'))),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import UserCreationView, UserListView, UserUpdateView, VoteView, ExamVoteCreateView, \
    ExamVoteUpdateView, ExamVoteDeleteView, ProfileView

app_name = 'users'

urlpatterns = [
    path('signup/', UserCreationView.as_view(), name="signup"),
    path('<int:pk>/', ProfileView.as_view(), name="profile"),
    path('<int:pk>/update/', UserUpdateView.as_view(), name="update"),
    path('', UserListView.as_view(), name="list"),
    path('vote/<int:pk>', VoteView.as_view(), name="vote-user"),
    path('add-mark', ExamVoteCreateView.as_view(), name="add-mark"),
    path('mark/<int:pk>/update', ExamVoteUpdateView.as_view(), name="update-mark"),
    path('mark/<int:pk>/delete', ExamVoteDeleteView.as_view(), name="delete-mark"),
]

forum/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from tinymce.models import HTMLField
from users.models import UniUser
from django.utils.timezone import now


class Topic(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False, unique=True)
    is_exam = models.BooleanField(blank=False, null=False)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    content = HTMLField()
    author = models.ForeignKey(UniUser, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True, editable=False)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    likes = models.ManyToManyField(UniUser, symmetrical=False, related_name="likes", blank=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = HTMLField()
    author = models.ForeignKey(UniUser, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True, editable=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    likes = models.ManyToManyField(UniUser, symmetrical=False, related_name="comment_likes", blank=True)

    def __str__(self):
        return self.post.title+" - "+self.author.username

forum/forms.py
from django import forms
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _

from .models import Post, Topic, Comment


class TopicCreationForm(forms.ModelForm):

    class Meta(forms.ModelForm):
        model = Topic
        fields = ("name", "is_exam")
        success_url = reverse_lazy('forum:topics')
        labels = {
            'is_exam': _('Is the topic an exam?'),
        }


class TopicUpdateForm(forms.ModelForm):

    class Meta(forms.ModelForm):
        model = Topic
        fields = ("name", "is_exam")
        success_url = reverse_lazy('forum:topics')
        labels = {
            'is_exam': _('Is the topic an exam?'),
        }


class PostCreationForm(forms.ModelForm):

    class Meta(forms.ModelForm):
        model = Post
        fields = ("title", "content")


class PostUpdateForm(forms.ModelForm):

    class Meta(forms.ModelForm):
        model = Post
        fields = ("title", "content")

class CommentCreationForm(forms.ModelForm):

    class Meta(forms.ModelForm):
        model = Comment
        fields = ("content",)

class CommentUpdateForm(forms.ModelForm):

    class Meta(forms.ModelForm):
        model = Comment
        fields = ("content",)

forum/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from .mixins import PermOrAuthorMixin
from .models import Topic, Post, Comment
from .forms import TopicCreationForm, TopicUpdateForm, PostCreationForm, PostUpdateForm, CommentCreationForm, \
    CommentUpdateForm
from django.db.models import Q, Count


class TopicListView(ListView):
    model = Topic
    template_name = 'forum/topics.html'

    ordering = ['name']


class TopicCreateView(SuccessMessageMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'forum.add_topic'
    form_class = TopicCreationForm
    model = Topic
    template_name = "forum/add_topic.html"
    success_url = reverse_lazy('forum:topics')
    success_message = "Topic created successfully!"


class TopicUpdateView(SuccessMessageMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'forum.change_topic'
    model = Topic
    template_name = 'forum/update_topic.html'
    success_url = reverse_lazy('forum:topics')
    form_class = TopicUpdateForm
    success_message = "Topic updated successfully!"


class TopicDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'forum.delete_topic'
    model = Topic
    template_name = 'forum/delete_topic.html'
    success_url = reverse_lazy('forum:topics')
    success_message = "Topic deleted successfully!"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(TopicDeleteView, self).delete(request, *args, **kwargs)


class TopicView(ListView):
    model = Post
    template_name = 'forum/view_topic.html'
    paginate_by = 2

    def get_queryset(self):
        query = self.request.GET.get("query")
        objects = self.model.objects.all()
        if query:
            objects = objects.filter(Q(topic=self.kwargs['pk']) &
                                     Q(title__icontains=query) | Q(content__icontains=query))
        else:
            objects = objects.filter(topic=self.kwargs['pk'])

        order = self.request.GET.get("order")
        if order == "least_recent":
            objects = objects.order_by("created_on")
        elif order == "most_recent":
            objects = objects.order_by("-created_on")
        elif order == "least_liked":
            objects = objects.annotate(num_likes=Count("likes")).order_by("num_likes")
        elif order == "most_liked":
            objects = objects.annotate(num_likes=Count("likes")).order_by("-num_likes")
        else:
            objects = objects.order_by("-created_on")

        return objects

    def get_context_data(self, **kwargs):
        context = super(TopicView, self).get_context_data(**kwargs)
        context['topic'] = get_object_or_404(Topic, pk=self.kwargs['pk'])
        context['search'] = ""
        context['order'] = ""
        if self.request.GET.get("query") is not None:
            context['search'] = self.request.GET.get("query")
        if self.request.GET.get("order") is not None:
            context['order'] = self.request.GET.get("order")
        return context


class PostCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    form_class = PostCreationForm
    template_name = "forum/add_post.html"
    model = Post
    success_message = "Post created successfully!"

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('forum:view-topic', kwargs={'pk': pk})

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.topic = get_object_or_404(Topic, pk=self.kwargs['pk'])
        return super().form_valid(form)


class PostDeleteView(PermOrAuthorMixin, DeleteView):
    perm_required = "forum.delete_post"
    model = Post
    template_name = 'forum/delete_post.html'
    success_message = "Post deleted successfully!"

    def get_success_url(self):
        return reverse_lazy('forum:view-topic', kwargs={"pk": self.get_object().topic.pk})

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(PostDeleteView, self).delete(request, *args, **kwargs)


class PostUpdateView(SuccessMessageMixin, PermOrAuthorMixin, UpdateView):
    perm_required = "forum.change_post"
    model = Post
    template_name = 'forum/update_post.html'
    form_class = PostUpdateForm
    success_message = "Post updated successfully!"

    def get_success_url(self):
        return reverse_lazy('forum:view-topic', kwargs={"pk": self.get_object().topic.pk})


class PostView(LoginRequiredMixin, ListView):
    model = Comment
    template_name = 'forum/view_post.html'
    paginate_by = 2

    def get_queryset(self):
        objects = self.model.objects.all()

        objects = objects.filter(post=self.kwargs['pk']).order_by("created_on")

        return objects

    def get_context_data(self, **kwargs):
        context = super(PostView, self).get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        context['form'] = CommentCreationForm()
        return context

    def get_success_url(self):
        return reverse_lazy('forum:view-post', kwargs={"pk": self.kwargs['pk']})


class CommentCreateView(LoginRequiredMixin, View):
    success_message = "Comment added successfully!"

    def post(self, request, *args, **kwargs):
        form = CommentCreationForm(request.POST)
        form.instance.author = self.request.user
        form.instance.post = get_object_or_404(Post, id=self.kwargs['pk'])
        if form.is_valid():
            messages.success(self.request, self.success_message)
            form.save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class CommentDeleteView(PermOrAuthorMixin, DeleteView):
    perm_required = "forum.delete_comment"
    model = Comment
    template_name = 'forum/delete_comment.html'
    success_message = "Comment deleted successfully!"

    def get_context_data(self, **kwargs):
        context = super(CommentDeleteView, self).get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.get_object().post.pk)
        return context

    def get_success_url(self):
        return reverse_lazy('forum:view-post', kwargs={"pk": self.get_object().post.pk})

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(CommentDeleteView, self).delete(request, *args, **kwargs)


class CommentUpdateView(SuccessMessageMixin, PermOrAuthorMixin, UpdateView):
    perm_required = "forum.change_comment"
    model = Comment
    template_name = 'forum/update_comment.html'
    form_class = CommentUpdateForm
    success_message = "Comment updated successfully!"

    def get_context_data(self, **kwargs):
        context = super(CommentUpdateView, self).get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.get_object().post.pk)
        return context

    def get_success_url(self):
        return reverse_lazy('forum:view-post', kwargs={"pk": self.get_object().post.pk})


class PostLikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        post_liked = get_object_or_404(Post, id=self.kwargs['pk'])
        if post_liked.likes.filter(id=request.user.id).exists():
            post_liked.likes.remove(request.user)
        else:
            post_liked.likes.add(request.user)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class CommentLikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        comment_liked = get_object_or_404(Comment, id=self.kwargs['pk'])
        if comment_liked.likes.filter(id=request.user.id).exists():
            comment_liked.likes.remove(request.user)
        else:
            comment_liked.likes.add(request.user)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

forum/templates/forum/add_post.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Add Post{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Add Post</h1>
        </div>
    </div>
    <form method="POST" >
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Add Post</button>
    </form>

{% endblock %}

forum/templates/forum/add_topic.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Add Topic{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Add Topic</h1>
        </div>
    </div>
    <form method="POST" >
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Add Topic</button>
    </form>

{% endblock %}

forum/templates/forum/delete_post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Delete Post{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Delete Post</h1>
        </div>
    </div>
    <form method="POST" class="mt-4" >
        {% csrf_token %}
        <h3 class="font-weight-light">Are you sure you want to delete <b>{{ object.name }}</b> post?</h3>
        <button type="submit" class="btn btn-danger mt-4">Delete Post</button>
    </form>

{% endblock %}

forum/templates/forum/delete_topic.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Delete Topic{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Delete Topic</h1>
        </div>
    </div>
    <form method="POST" class="mt-4" >
        {% csrf_token %}
        <h3 class="font-weight-light">Are you sure you want to delete <b>{{ object.name }}</b> topic?</h3>
        <button type="submit" class="btn btn-danger mt-4">Delete Topic</button>
    </form>

{% endblock %}

forum/templates/forum/topics.html
{% extends 'base.html' %}
{% load static %}
{% load has_group %}
{% block title %}Topics{% endblock %}

{% block content %}
    <h1>Topics</h1>
    {% if user|has_group:"mods" %}
        <div class="row">
            <div class="col-md-12 text-center">
                <a href="{% url 'forum:add-topic' %}" class="btn btn-primary btn-lg" ><i class="bi bi-plus-lg"></i></a>
            </div>
        </div>
    {% endif %}
    {% for topic in object_list %}
        <div class="card mt-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-9">
                        <a href="{% url "forum:view-topic" topic.pk %}" class="stretched-link"></a>
                        <h3>{{ topic.name }}</h3>
                    </div>
                    <div class="col-3 float-right">
                        <a href="{% url 'events:events' topic.pk %}" class="btn btn-outline-primary mb-2 mr-2" ><i class="bi bi-calendar"></i></a>
                        {% if topic.is_exam %}
                            <a href="{% url 'reviews:reviews' topic.pk %}" class="btn btn-outline-primary mb-2 mr-2" ><i class="bi bi-bar-chart-fill"></i></a>
                        {% endif %}
                        {% if user|has_group:"mods" %}
                            <a href="{% url 'forum:delete-topic' topic.pk %}" class="btn btn-danger mb-2 mr-2" ><i class="bi bi-trash"></i></a>
                            <a href="{% url 'forum:update-topic' topic.pk %}" class="btn btn-secondary mb-2" ><i class="bi bi-pencil"></i></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

forum/templates/forum/view_post.html
{% extends 'base.html' %}
{% load static %}
{% load has_group %}
{% load crispy_forms_tags %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>{{ post.title }}</h1>
        </div>

    </div>


    <ul class="list-unstyled mt-4">


        <li  class="media border p-3">
            <a href="{% url "users:profile" post.author.pk %}">
            {% if post.author.propic %}
                <img class="mr-3 img-fluid img-thumbnail rounded-circle" width="100px" src="{{ post.author.propic.url }}">
            {% else %}
                <img class="mr-3 img-fluid img-thumbnail rounded-circle" width="100px" src="{% static 'users/avatar-placeholder.png' %}">
            {% endif %}
            </a>
            <div class="media-body">

                <h6><a href="{% url "users:profile" post.author.pk %}" class="text-dark">{{ post.author.username }}</a> - <small><i>{{ post.created_on }}</i></small></h6>
                <div>
                    {{ post.content|safe }}
                </div>
                <br/>
                {% for comment in object_list %}
                    <div class="media p-3">
                        <a href="{% url "users:profile" comment.author.pk %}" class="mr-3">

                            {% if comment.author.propic %}
                                <img class="mr-3 img-fluid img-thumbnail rounded-circle" width="100px" src="{{ comment.author.propic.url }}">
                            {% else %}
                                <img class="mr-3 img-fluid img-thumbnail rounded-circle" width="100px" src="{% static 'users/avatar-placeholder.png' %}">
                            {% endif %}
                        </a>
                        <div class="media-body">
                            <div class="row">
                                <div class="col-10">
                                    <h6><a href="{% url "users:profile" comment.author.pk %}" class="text-dark">{{ comment.author.username }}</a> - <small><i>{{ comment.created_on }}</i></small></h6>
                                    <p>{{ comment.content|safe }}</p>
                                </div>
                                <div class="col-2 float-right">
                                    {% if user|has_group:"mods" or user == comment.author %}
                                        <a href="{% url 'forum:delete-comment' comment.pk %}" class="btn btn-danger mb-2 mr-2" ><i class="bi bi-trash"></i></a>
                                        <a href="{% url 'forum:update-comment' comment.pk %}" class="btn btn-secondary mb-2 mr-2" ><i class="bi bi-pencil"></i></a>
                                    {% endif %}
                                    <form method="POST" action="{% url 'forum:like-comment' comment.pk %}" class="form-check-inline">
                                        {% csrf_token %}
                                        <h2 style="display:inline"><button type="submit" class="btn btn-outline-danger">{{ comment.likes.count }} <i class="bi bi-heart{% if user in comment.likes.all %}-fill{% endif %}"></i></button></h2>
                                    </form>
                                </div>
                            </div>
                        </div>

                    </div>
                {% endfor %}
            </div>
            <div class="col-2 float-right">
                {% if user|has_group:"mods" or user == post.author %}
                    <a href="{% url 'forum:delete-post' post.pk %}" class="btn btn-danger mb-2 mr-2" ><i class="bi bi-trash"></i></a>
                    <a href="{% url 'forum:update-post' post.pk %}" class="btn btn-secondary mb-2 mr-2" ><i class="bi bi-pencil"></i></a>
                {% endif %}
                <form method="POST" action="{% url 'forum:like-post' post.pk %}" class="form-check-inline">
                    {% csrf_token %}
                    <h2 style="display:inline"><button type="submit" class="btn btn-outline-danger">{{ post.likes.count }} <i class="bi bi-heart{% if user in post.likes.all %}-fill{% endif %}"></i></button></h2>
                </form>
            </div>
        </li>


    </ul>


    <nav aria-label="..." class="mt-5">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1" tabindex="-1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">{{ page_obj.previous_page_number }}</a>
                </li>
            {% endif %}

            <li class="page-item active">
                <a class="page-link" href="" id="actual-page-link">{{ page_obj.number }}<span class="sr-only">(current)</span></a>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                </li>

            {% endif %}

        </ul>
    </nav>
    <div>
        <form method="POST" action="{% url 'forum:add-comment' post.pk %}">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Add Comment</button>
        </form>
    </div>


{% endblock %}
{% block javascript %}
        <script>
        links = document.getElementsByClassName("page-link")
        for (var i = 0; i < links.length; i++) {
            if(links[i].id != "actual-page-link"){
                links[i].href += "&query={{ search }}"
                links[i].href += "&order={{ order }}"
            }

        }

    </script>
{% endblock %}

forum/templates/forum/view_topic.html
{% extends 'base.html' %}
{% load static %}
{% load has_group %}
{% block title %}{{ topic.name }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1 class="d-inline">{{ topic.name }}</h1>
            <div class="d-inline">
                <a href="{% url 'events:events' topic.pk %}" class="btn btn-outline-primary ml-3 mb-3" ><i class="bi bi-calendar"></i></a>
            </div>
            {% if topic.is_exam %}
                <div class="d-inline">
                    <a href="{% url 'reviews:reviews' topic.pk %}" class="btn btn-outline-primary ml-3 mb-3" ><i class="bi bi-bar-chart-fill"></i></a>
                </div>
            {% endif %}
        </div>
    </div>

    {% if user.is_authenticated %}
        <form action="{% url "forum:view-topic" topic.pk %}" method="GET">
            <div class="input-group mb-3 mt-3">
                <div class="input-group-prepend">
                    <a href="{% url 'forum:add-post' topic.pk %}" class="btn btn-success" ><i class="bi bi-plus-lg"></i></a>
                </div>

                <input name="query" type="text" class="form-control" placeholder="Search post" aria-label="query" {% if search %} value="{{ search }}" {% endif %}>

                <div class="input-group-append">
                    <select class="custom-select" aria-label="Select order" name="order">
                        <option {% if order == "most_recent" %}selected{% endif %} value="most_recent">Most Recent</option>
                        <option {% if order == "least_recent" %}selected{% endif %} value="least_recent" >Least Recent</option>
                        <option {% if order == "most_liked" %}selected{% endif %} value="most_liked" >Most Liked</option>
                        <option {% if order == "least_liked" %}selected{% endif %} value="least_liked" >Least Liked</option>
                    </select>
                    <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </div>

        </form>


        <ul class="list-unstyled mt-4">
            {% for post in object_list %}

                <li  class="media border p-3">
                    <a href="{% url "users:profile" post.author.pk %}">
                    {% if post.author.propic %}
                        <img class="mr-3 img-fluid img-thumbnail rounded-circle" width="100px" src="{{ post.author.propic.url }}">
                    {% else %}
                        <img class="mr-3 img-fluid img-thumbnail rounded-circle" width="100px" src="{% static 'users/avatar-placeholder.png' %}">
                    {% endif %}
                    </a>
                    <div class="media-body">
                        <h3 class="mt-0"><a href="{% url 'forum:view-post' post.pk %}">{{ post.title }}</a></h3>
                        <h6><a href="{% url "users:profile" post.author.pk %}" class="text-dark">{{ post.author.username }}</a> - <small><i>{{ post.created_on }}</i></small></h6>
                        <div>
                            {{ post.content|safe|truncatewords:20 }}
                        </div>
                    </div>
                    <div class="col-2 float-right">
                        {% if user|has_group:"mods" or user == post.author %}
                            <a href="{% url 'forum:delete-post' post.pk %}" class="btn btn-danger mb-2 mr-2" ><i class="bi bi-trash"></i></a>
                            <a href="{% url 'forum:update-post' post.pk %}" class="btn btn-secondary mb-2 mr-2" ><i class="bi bi-pencil"></i></a>
                        {% endif %}
                        <form method="POST" action="{% url 'forum:like-post' post.pk %}" class="form-check-inline">
                            {% csrf_token %}
                            <h2 style="display:inline"><button type="submit" class="btn btn-outline-danger">{{ post.likes.count }} <i class="bi bi-heart{% if user in post.likes.all %}-fill{% endif %}"></i></button></h2>
                        </form>
                    </div>
                </li>
            {% endfor %}
        </ul>


        <nav aria-label="..." class="mt-5">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" tabindex="-1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">{{ page_obj.previous_page_number }}</a>
                    </li>
                {% endif %}

                <li class="page-item active">
                    <a class="page-link" href="" id="actual-page-link">{{ page_obj.number }}<span class="sr-only">(current)</span></a>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                    </li>

                {% endif %}

            </ul>
        </nav>
    {% endif %}


{% endblock %}

{% block javascript %}
        <script>
        links = document.getElementsByClassName("page-link")
        for (var i = 0; i < links.length; i++) {
            if(links[i].id != "actual-page-link"){
                links[i].href += "&query={{ search }}"
                links[i].href += "&order={{ order }}"
            }

        }

    </script>
{% endblock %}