forum/urls.py
from django.urls import path
from .views import CommentCreateView, TopicListView, TopicCreateView, TopicUpdateView, TopicDeleteView, TopicView, \
    PostCreateView, \
    PostUpdateView, PostDeleteView, PostView, CommentDeleteView, CommentUpdateView, PostLikeView, CommentLikeView

app_name = 'forum'

urlpatterns = [
    path('', TopicListView.as_view(), name="topics"),
    path('add-topic', TopicCreateView.as_view(), name="add-topic"),
    path('topic/<int:pk>/update/', TopicUpdateView.as_view(), name="update-topic"),
    path('topic/<int:pk>/delete/', TopicDeleteView.as_view(), name="delete-topic"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="update-post"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="delete-post"),
    path('post/<int:pk>/', PostView.as_view(), name="view-post"),
    path('topic/<int:pk>/', TopicView.as_view(), name="view-topic"),
    path('topic/<int:pk>/add-post', PostCreateView.as_view(), name="add-post"),
    path('post/<int:pk>/add-comment', CommentCreateView.as_view(), name="add-comment"),
    path('comment/<int:pk>/delete-comment', CommentDeleteView.as_view(), name="delete-comment"),
    path('comment/<int:pk>/update-comment', CommentUpdateView.as_view(), name="update-comment"),
    path('post/<int:pk>/like-post', PostLikeView.as_view(), name="like-post"),
    path('comment/<int:pk>/like-comment', CommentLikeView.as_view(), name="like-comment"),
]

uniforum/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import Homepage

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'))),
    path('users/', include('django.contrib.auth.urls')),
    path('forum/', include(('forum.urls', 'forum'))),
    path('events/', include(('events.urls', 'events'))),
    path('reviews/', include(('reviews.urls', 'reviews'))),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import UserCreationView, UserListView, UserUpdateView, VoteView, ExamVoteCreateView, \
    ExamVoteUpdateView, ExamVoteDeleteView, ProfileView

app_name = 'users'

urlpatterns = [
    path('signup/', UserCreationView.as_view(), name="signup"),
    path('<int:pk>/', ProfileView.as_view(), name="profile"),
    path('<int:pk>/update/', UserUpdateView.as_view(), name="update"),
    path('', UserListView.as_view(), name="list"),
    path('vote/<int:pk>', VoteView.as_view(), name="vote-user"),
    path('add-mark', ExamVoteCreateView.as_view(), name="add-mark"),
    path('mark/<int:pk>/update', ExamVoteUpdateView.as_view(), name="update-mark"),
    path('mark/<int:pk>/delete', ExamVoteDeleteView.as_view(), name="delete-mark"),
]

users/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class UniUser(AbstractUser):
    email = models.EmailField(_('email address'), blank=False, unique=True)
    propic = models.ImageField(upload_to='images/', null=True, blank=True)
    votes = models.ManyToManyField("self", symmetrical=False, blank=True)
    private = models.BooleanField(blank=False, null=False)


from forum.models import Topic


class UserExamVote(models.Model):
    exam = models.ForeignKey(Topic, blank=False, null=False, on_delete=models.CASCADE)
    user = models.ForeignKey(UniUser, blank=False, null=False, on_delete=models.CASCADE)
    vote = models.IntegerField(validators=[MaxValueValidator(30), MinValueValidator(18)], blank=False, null=False)
    honors = models.BooleanField(blank=False, null=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["exam", "user"],
                name="A user can have just one vote per exam",
            )
        ]

    def clean(self, *args, **kwargs):
        super().clean(*args, **kwargs)
        if self.vote < 30 and self.honors:
            raise ValidationError("Honors could be assigned only if vote is equal to 30")
        if not self.exam.is_exam:
            raise ValidationError("Topic must be an exam")

    def __str__(self):
        return f"{self.user} - {self.exam}"

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _

from forum.models import Topic
from .models import UniUser, UserExamVote


class UniUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = UniUser
        fields = ("username", "email", "first_name", "last_name", "propic", "private")
        success_url = reverse_lazy('homepage')
        labels = {
            'propic': _('Profile Picture'),
        }


class UniUserChangeForm(UserChangeForm):
    password = None

    class Meta(UserChangeForm):
        model = UniUser
        fields = ("username", "email", "first_name", "last_name", "propic", "private")
        labels = {
            'propic': _('Profile Picture'),
        }


class ExamVoteCreationForm(forms.ModelForm):
    class Meta:
        model = UserExamVote
        fields = ('exam', 'vote', 'honors', )

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super(ExamVoteCreationForm, self).__init__(*args, **kwargs)
        exams = Topic.objects.filter(is_exam=True)
        exams_user = UserExamVote.objects.filter(user=self.request.user).values('exam')
        exams_user = [el["exam"] for el in exams_user]
        self.fields['exam'].queryset = exams.exclude(id__in=exams_user)


class ExamVoteUpdateForm(forms.ModelForm):
    class Meta:
        model = UserExamVote
        fields = ('vote', 'honors', )

users/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, ListView, TemplateView, UpdateView, DeleteView, DetailView

from forum.models import Topic
from .forms import ExamVoteCreationForm, UniUserCreationForm, UniUserChangeForm, ExamVoteUpdateForm
from .models import UniUser, UserExamVote
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


class UserCreationView(SuccessMessageMixin, CreateView):

    form_class = UniUserCreationForm
    template_name = 'users/creation.html'
    success_url = reverse_lazy('login')
    success_message = "User created successfully!"


class ProfileView(DetailView):
    template_name = "users/profile.html"
    model = UniUser

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        if self.request.user == self.get_object() or not self.get_object().private:
            context['marks'] = UserExamVote.objects.all().filter(user=self.get_object())
        return context


class UserUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = UniUser
    template_name = 'users/update.html'
    form_class = UniUserChangeForm
    success_message = "User updated successfully!"

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('users:profile', kwargs={'pk': pk})

    def get_object(self, *args, **kwargs):
        obj = super(UserUpdateView, self).get_object(*args, **kwargs)
        if not obj.id == self.request.user.id:
            raise PermissionDenied
        return obj


class UserListView(LoginRequiredMixin, ListView):
    model = UniUser
    template_name = 'users/list.html'
    paginate_by = 2

    def get_queryset(self):
        username = self.request.GET.get("username")

        object_list = self.model.objects.all()
        if username:
            object_list = object_list.filter(username__icontains=username).order_by('username')
        return object_list

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['search'] = ""
        if self.request.GET.get("username") is not None:
            context['search'] = self.request.GET.get("username")
        return context


class VoteView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        user_voted = get_object_or_404(UniUser, id=self.kwargs['pk'])
        if user_voted.votes.filter(id=request.user.id).exists():
            user_voted.votes.remove(request.user)
        else:
            user_voted.votes.add(request.user)
        self.check_mod(user_voted)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    def check_mod(self, user_voted):
        n_users = UniUser.objects.count()
        min_votes = max(int(15*n_users/100), 2)

        mods, created = Group.objects.get_or_create(name="mods")
        if created:
            mods.name = "mods"
            content_type_topic = ContentType.objects.get(app_label='forum', model='topic')
            content_type_post = ContentType.objects.get(app_label='forum', model='post')
            content_type_comment = ContentType.objects.get(app_label='forum', model='comment')
            content_type_events = ContentType.objects.get(app_label='events', model='event')
            content_type_reviews = ContentType.objects.get(app_label='reviews', model='review')
            # get all permssions for these models
            perms = [Permission.objects.filter(content_type=content_type_topic),
                     Permission.objects.filter(content_type=content_type_post),
                     Permission.objects.filter(content_type=content_type_comment),
                     Permission.objects.filter(content_type=content_type_events),
                     Permission.objects.filter(content_type=content_type_reviews)]

            for e in perms:
                for p in e:
                    mods.permissions.add(p)
            mods.save()

        if user_voted.votes.count() >= min_votes:
            user_voted.groups.add(mods)
        else:
            user_voted.groups.remove(mods)


class ExamVoteCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    form_class = ExamVoteCreationForm
    template_name = "users/add_mark.html"
    model = UserExamVote
    success_message = "Mark added successfully!"

    def get_success_url(self):
        pk = self.request.user.pk
        return reverse_lazy('users:profile', kwargs={'pk': pk})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ExamVoteUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = UserExamVote
    template_name = 'users/update_mark.html'
    form_class = ExamVoteUpdateForm
    success_message = "Mark updated successfully!"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not request.user == self.object.user:
            return HttpResponseForbidden()
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        pk = self.request.user.pk
        return reverse_lazy('users:profile', kwargs={'pk': pk})


class ExamVoteDeleteView(LoginRequiredMixin, DeleteView):
    model = UserExamVote
    template_name = 'users/delete_mark.html'
    success_message = "Mark deleted successfully!"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not request.user == self.object.user:
            return HttpResponseForbidden()
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        pk = self.request.user.pk
        return reverse_lazy('users:profile', kwargs={'pk': pk})

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(ExamVoteDeleteView, self).delete(request, *args, **kwargs)

users/templates/users/add_mark.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add mark{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Add mark</h1>
        </div>
    </div>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Add mark</button>
    </form>
{% endblock %}

users/templates/users/creation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Sign Up</h1>
        </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
{% endblock %}

users/templates/users/delete_mark.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Delete Mark{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Delete Mark</h1>
        </div>
    </div>
    <form method="POST" class="mt-4" >
        {% csrf_token %}
        <h3 class="font-weight-light">Are you sure you want to delete <b>{{ object.exam.name }}</b> mark?</h3>
        <button type="submit" class="btn btn-danger mt-4">Delete Mark</button>
    </form>

{% endblock %}

users/templates/users/list.html
{% extends 'base.html' %}
{% load static %}
{% load has_group %}
{% block title %}Users{% endblock %}

{% block content %}
    <h1>Users</h1>
    <form action="{% url "users:list" %}" method="GET">
        <div class="input-group mb-3">
            {% if search %}
                <input name="username" type="text" class="form-control" placeholder="Search user" aria-label="Username" value="{{ search }}">
            {% else %}
                <input name="username" type="text" class="form-control" placeholder="Search user" aria-label="Username">
            {% endif %}
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Search</button>
            </div>
        </div>

    </form>
    {% for us in object_list %}
        <div class="card mt-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-2 align-self-center">
                        <a href="{% url "users:profile" us.pk %}">
                        {% if us.propic %}
                            <img class="img-fluid img-thumbnail" src="{{ us.propic.url }}">
                        {% else %}
                            <img class="img-fluid img-thumbnail" src="{% static 'users/avatar-placeholder.png' %}">
                        {% endif %}
                        </a>
                    </div>
                    <div class="col-7 align-self-center">
                        <h3>{% if us|has_group:"mods" %}<i class="bi bi-award-fill"></i> {% endif %}<a href="{% url "users:profile" us.pk %}">{{ us.username }}</a></h3>
                        <p>{{ us.first_name }} {{ us.last_name }}</p>
                    </div>
                    <div class="col-3  float-right align-self-center text-center">
                        <form method="POST" action="{% url 'users:vote-user' us.pk %}">
                            {% csrf_token %}
                            {% if user in us.votes.all %}
                                <button id="vote" type="submit" name="user_id" class="btn btn-outline-danger btn-lg mb-1" value="{{ us.id }}">Unvote</button>
                            {% else %}
                                <button id="vote" type="submit" name="user_id" class="btn btn-success btn-lg mb-1" value="{{ us.id }}">Vote</button>
                            {% endif %}
                            <h4><span class="badge badge-secondary">{{ us.votes.count }}</span></h4>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}


    <nav aria-label="..." class="mt-5">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1" tabindex="-1">First</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">{{ page_obj.previous_page_number }}</a>
            </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="" id="actual-page-link">{{ page_obj.number }}<span class="sr-only">(current)</span></a>
        </li>
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            </li>

        {% endif %}

      </ul>
    </nav>


{% endblock %}
{% block javascript %}
    <script>
        links = document.getElementsByClassName("page-link")
        for (var i = 0; i < links.length; i++) {
            if(links[i].id != "actual-page-link"){
                links[i].href += "&username={{ search }}"
            }

        }

    </script>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
    {% block title %}My Profile{% endblock %}
{% endblock %}
{% block content %}
    <h1>My Profile</h1>
    <div class="row mt-4 mb-4">
        <div class="col-3">
            {% if object.propic %}
                <img class="img-fluid img-thumbnail" src="{{ object.propic.url }}">
            {% else %}
                <img class="img-fluid img-thumbnail" src="{% static 'users/avatar-placeholder.png' %}">
            {% endif %}

        </div>

        <div class="col-9">
            <h2>{{ object.username }}</h2>
            <h4 class="font-weight-light">{{ object.first_name }} {{ object.last_name }}</h4>
            <h4 class="font-weight-light">{{ object.email }}</h4>
            {% if object == user %}
                <a class="btn btn-secondary mt-4" href="{% url "users:update" object.id %}"><i class="bi bi-pencil"></i></a>
                <a class="btn btn-info mt-4" href="{% url "password_change" %}">Change password</a>
                <a class="btn btn-success mt-4" href="{% url "users:add-mark" %}">Add mark</a>
            {% endif %}
        </div>

    </div>

    <h3>Exams</h3>
    {% if not object.private or object == user %}
        <div class="mt-4">
            <table id="table-exams" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Mark</th>
                        {% if object == user %}
                            <th>Edit</th>
                            <th>Delete</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for mark in marks %}
                        <tr>
                            <td><a href="{% url "forum:view-topic" mark.exam.pk %}">{{ mark.exam.name }}</a></td>
                            <td>{{ mark.vote }}{% if mark.honors %} L{% endif %}</td>
                            {% if object == user %}
                                <td class="text-center align-middle"><a class="btn btn-secondary" href="{% url "users:update-mark" mark.pk %}"><i class="bi bi-pencil"></i></a></td>
                                <td class="text-center align-middle"><a class="btn btn-danger" href="{% url "users:delete-mark" mark.pk %}">Delete</a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}

                </tbody>

            </table>
        </div>
    {% else %}
        <h5>This profile is private!</h5>
    {% endif %}


{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function() {
            $('#table-exams').DataTable();
        } );
    </script>

{% endblock %}

users/templates/users/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit profile{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Edit Profile</h1>
        </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
{% endblock %}

users/templates/users/update_mark.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit mark{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Edit mark: {{ object.exam.name }}</h1>
        </div>
    </div>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
{% endblock %}