events/urls.py
from django.urls import path
from .views import ListEventsView, DetailEventView, EventCreateView, EventDeleteView, EventUpdateView

app_name = 'events'

urlpatterns = [
    path('topic/<int:pk>', ListEventsView.as_view(), name='events'),
    path('<int:pk>', DetailEventView.as_view(), name='view-event'),
    path('<int:pk>/add-event', EventCreateView.as_view(), name="add-event"),
    path('<int:pk>/delete-event', EventDeleteView.as_view(), name="delete-event"),
    path('<int:pk>/update-event', EventUpdateView.as_view(), name="update-event"),
]

forum/urls.py
from django.urls import path
from .views import CommentCreateView, TopicListView, TopicCreateView, TopicUpdateView, TopicDeleteView, TopicView, \
    PostCreateView, \
    PostUpdateView, PostDeleteView, PostView, CommentDeleteView, CommentUpdateView, PostLikeView, CommentLikeView

app_name = 'forum'

urlpatterns = [
    path('', TopicListView.as_view(), name="topics"),
    path('add-topic', TopicCreateView.as_view(), name="add-topic"),
    path('topic/<int:pk>/update/', TopicUpdateView.as_view(), name="update-topic"),
    path('topic/<int:pk>/delete/', TopicDeleteView.as_view(), name="delete-topic"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="update-post"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="delete-post"),
    path('post/<int:pk>/', PostView.as_view(), name="view-post"),
    path('topic/<int:pk>/', TopicView.as_view(), name="view-topic"),
    path('topic/<int:pk>/add-post', PostCreateView.as_view(), name="add-post"),
    path('post/<int:pk>/add-comment', CommentCreateView.as_view(), name="add-comment"),
    path('comment/<int:pk>/delete-comment', CommentDeleteView.as_view(), name="delete-comment"),
    path('comment/<int:pk>/update-comment', CommentUpdateView.as_view(), name="update-comment"),
    path('post/<int:pk>/like-post', PostLikeView.as_view(), name="like-post"),
    path('comment/<int:pk>/like-comment', CommentLikeView.as_view(), name="like-comment"),
]

uniforum/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import Homepage

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'))),
    path('users/', include('django.contrib.auth.urls')),
    path('forum/', include(('forum.urls', 'forum'))),
    path('events/', include(('events.urls', 'events'))),
    path('reviews/', include(('reviews.urls', 'reviews'))),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import UserCreationView, UserListView, UserUpdateView, VoteView, ExamVoteCreateView, \
    ExamVoteUpdateView, ExamVoteDeleteView, ProfileView

app_name = 'users'

urlpatterns = [
    path('signup/', UserCreationView.as_view(), name="signup"),
    path('<int:pk>/', ProfileView.as_view(), name="profile"),
    path('<int:pk>/update/', UserUpdateView.as_view(), name="update"),
    path('', UserListView.as_view(), name="list"),
    path('vote/<int:pk>', VoteView.as_view(), name="vote-user"),
    path('add-mark', ExamVoteCreateView.as_view(), name="add-mark"),
    path('mark/<int:pk>/update', ExamVoteUpdateView.as_view(), name="update-mark"),
    path('mark/<int:pk>/delete', ExamVoteDeleteView.as_view(), name="delete-mark"),
]

events/models.py
from django.db import models
from forum.models import Topic
from tinymce.models import HTMLField


class Event(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    start_date = models.DateField(blank=False, null=False)
    start_time = models.TimeField(blank=True, null=True)
    description = HTMLField(blank=True, null=True)

    def __str__(self):
        return f"{self.topic} - {self.title}"

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->

    {% block head %}
        <title>{% block title %}{% endblock %}</title>
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
    <a class="navbar-brand" href="/">UniForum</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'forum:topics' %}">Forum <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:list' %}">Users</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:profile' user.pk %}">Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
                </li>
            {% endif %}
        </ul>

    </div>
</nav>

<main role="main" class="container" style="margin-top:80px; margin-bottom:50px">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message | safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}

    {% block content %}
    {% endblock %}
</main>
    {% block javascript %}{% endblock %}


</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block head %}
    {% block title %}Homepage{% endblock %}
    <link href='https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.1/css/all.css' rel='stylesheet'>

    <link href='https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/main.min.css' rel='stylesheet' />
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/main.min.js'></script>

{% endblock %}


{% block content %}
    <h1>Homepage</h1>
    <h3 class="mt-4">Events</h3>
    <div id='calendar' class="mt-4" ></div>
{% endblock %}

{% block javascript %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {

                initialView: 'listMonth',
                themeSystem: 'bootstrap',
                headerToolbar: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
                },
                events: [
                    {% for event in event_list %}
                    {
                        title: '{{ event.topic.name }} - {{ event.title }}',
                        start: '{{ event.start_date.isoformat }}{% if event.start_time %} {{ event.start_time.isoformat }}{% endif %}',
                        url: '{% url 'events:view-event' event.pk %}',
                    },
                    {% endfor %}
                ]
            });
            calendar.setOption('height', 600);
            calendar.render();

        });
    </script>
{% endblock %}